version: "3"

services:
  pik4_web:
    container_name: pik4_web
    build:
      context: docker/app
      dockerfile: Dockerfile
    depends_on:
      - pik4_db
    ports:
      - "8888:80"
    volumes:
      - ./html:/var/www/html

  # MySQL
  pik4_db:
    container_name: pik4_db
    image: mysql:5.7
    platform: linux/x86_64
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  # phpMyAdmin
  pik4_pma:
    container_name: pik4_pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - pik4_db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=pik4_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "9999:80"
